version: 2
jobs:
  test:
    docker:
      - image: cimg/base:2021.07
    steps:
      - checkout
      - run:
          name: Install CPAN minus
          command: |
            curl -L https://cpanmin.us | perl - App::cpanminus
      - restore_cache:
          keys:
            - dependency-cache-{{ checksum ".perl-version" }}-{{ checksum "cpanfile" }}
      - run:
          name: Install local::lib
          command: |
            cpanm --notest --local-lib=local local::lib && echo "eval $(perl -I local/lib/perl5/ -Mlocal::lib)" >> ~/.bashrc
      - run:
          name: Install project dependencies
          command: |
            cpanm --installdeps -l local --notest .
      - save_cache:
          key: dependency-cache-{{ checksum ".perl-version" }}-{{ checksum "cpanfile" }}
          paths:
            - local
      - run:
          name: Test
          command: |
            PERL_TEST_HARNESS_DUMP_TAP=./test_output PERL5LIB=./src:./local/lib/perl5 prove --timer --formatter TAP::Formatter::JUnit src
      - store_test_results:
          path: ./test_output

workflows:
  version: 2
  test:
    jobs:
      - test
